default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: my_march_development

test:
  <<: *default
  database: my_march_test

development:
  <<: *default
  database: my_march_development
  username: postgres
  password: "edwinrotich"
  host: 127.0.0.1


  cable:
    <<: *default
    database: my_march_cable_production
